### PR TITLE
The variable dwSize overflows if larger than 4Gb

### PR DESCRIPTION
**Pull request by w5277c**
Hi, could you please add small fix?

[PacExtractor.java.txt](https://github.com/divinebird/pacextractor/files/6256972/PacExtractor.java.txt)

            PacHeader pacHeader = new PacHeader();
            if (unsigned(pacHeader.dwSize) != inFile.length()) {
               if(inFile.length() > 0x100000000l && unsigned(pacHeader.dwSize) == (inFile.length() - 0x100000000l))
                  System.out.println("\nWarning! Bin packet's size is not correct\n");                
               else
                  exit("Bin packet's size is not correct");
            }
            else if (!getString(pacHeader.szVersion).equals("BP_R1.0.0"))
                exit("Unsupported PAC version");

Best Regards,
Konstantin.

### CODE REVIEW

**Comment by divinebird** [comment]
I think you should make pull request to fork of @HemanthJabalpuri
I have no java sources here :)

**Comment by HemanthJabalpuri** [comment]
@w5277c
I am just a beginner to programming.
What I think is since it is only `int`, dwSize have to fit in it else exit. Since the header is made like that.
So it will surely exit if it overflows making us to assume it as a corrupted or unknown format of .pac.
May be I am wrong in this.

Thanks

**Comment by HemanthJabalpuri** [comment]
@divinebird
Can you please also see my C source changes at https://github.com/HemanthJabalpuri/pacextractor/blob/master/pacextractor.c

Those are made with my nano knowledge!

Thanks

**Comment by w5277c** [comment]
Hi,

But big PAC files exist, and(by some magic) the standard utility unpacks
them correctly, it looks like this utility has some algorithm for this
problem.

Anyway, here's a new version. The size of the partition can also overflow
and this complicates all current code.

I think, you can put this as additional information.
Perhaps it will be useful to someone.


Best Regards,
Konstantin.

пн, 5 апр. 2021 г. в 23:19, Hemanth ***@***.***>:

**Pull request closed without merging**
